plugins { id 'com.android.application' }

android {
    namespace 'com.xiaotao.workbench'
    compileSdk 35

    defaultConfig {
        applicationId 'com.xiaotao.workbench'
        minSdk 24
        targetSdk 35
        versionCode 3
        versionName '1.2.0'
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
}
